version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
     POSTGRES_USER: dante
     POSTGRES_PASSWORD: dante123456
     POSTGRES_DB: library
  # adminer:
  #   image: adminer:4.7.8-standalone
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  backend:
    build:
      context: .
    ports:
      - 8088:8088
    command: bash -c
      " ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py loaddata data.json
      && gunicorn drf.wsgi -b 0.0.0.0:8088 "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8008:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 8005:80
    depends_on:
      - nginx
